#!/usr/bin/env ruby
# encoding: utf-8

# May you recognize your weaknesses and share your strengths.
# May you share freely, never taking more than you give.
# May you find love and love everyone you find.

require 'docopt'
require 'git'
require 'pp'

# Git intercepts `git swear-stats --help`, so unfortunately most people won't
# see this usage message.  Docopt is still a great way to do parsing, though.
doc = <<DOCOPT
git-swear-stats

Usage:
   git-swear-stats [options]

Options:
   -h, --help        Show this screen.
   --debug           Print out debug messages.
   --include-merges  Look at merge commits.

DOCOPT
begin
   options = Docopt::docopt doc
rescue Docopt::Exit => e
   puts e.message
   exit 1
end
pp options if options['--debug']

swears = [
   %r{^(dip)?shit(ty)?$},
   %r{^(mother)?(fuck|fsck|eff)(ing|er|ed|head)?$},
   %r{^cunt$},
   %r{^cock(suck|sucker)?$},
   %r{^(ass|arse)(hole)?$},
   %r{^bitch(y)?$},
   %r{^wtf$},
   %r{^fag(got)?$},
   %r{^(god)?damn(ed|able)?$},
   %r{^bastard$},
   %r{^hell(ish)?$},
]

wordStats = {}
wordStats.default = 0
authorStats = {}

repo = Git.open '.'
# By default, we only get up to 30 commits in the log.  By digging through the
# source, I found that passing nil to repo.log() ends up setting the limit to
# nil, and thus giving us all commits.
print 'Reading in git log... '
log = repo.log nil
puts 'done!'

print 'Parsing commit messages'
log.each_with_index do |commit, i|
   # Merges often have data in them from other commits, pull request
   # descriptions, etc., so it's not really fair to count them.
   # Git::Log unfortunately appears to have no way of passing --no-merges
   # through to the underlying binary, so we have to check merges on a
   # commit-by-commit basis instead.
   next if not options['--include-merges'] and commit.parents.count > 1
   
   author = commit.author.name
   if not authorStats.key? author
      authorStats[author] = {}
      authorStats[author].default = 0
   end
   
   # Splitting on words makes our regexes a little simpler.
   commit.message.split(%r{[ \-_.,!?;:*"'\n]}).each do |word|
      word.downcase! # A little bit of normalization.
      swears.each do |swear|
         if word =~ swear
            wordStats[word] += 1
            authorStats[author][word] += 1
            if options['--debug']
               puts '-'*80
               puts author
               puts commit.message
               puts '-'*80
            end
         end
      end
   end
   # For large repos, parsing can take a while; let users know something is
   # happening.
   print '.' if i % 100 == 0
end

# People who haven't sworn at all aren't very interesting.
authorStats.delete_if {|author, swears| swears.empty?}

puts
pp wordStats
pp authorStats

